import Head from "next/head";
import { NextPage } from "next";
import React, { useMemo } from "react";

import { extractAssets } from "@/utils/helpers";
import AssetsGrid from "@/components/AssetsGrid";
import Folder from "@/components/Folder";
import { css } from "../../styled-system/css";
import { useFileStore } from "@/stores/files";
import Gallery from "@/components/Gallery";

const Home: NextPage = () => {
  const files = useFileStore((state) => state.files);

  console.log("Files", files);

  // @ts-ignore
  const directories: DirectoryType[] = files.filter(
    (file) => file.type === "directory",
  );

  const assets = useMemo(() => {
    const assets: AssetType[] = directories
      .map((directory) => extractAssets(directory))
      .flat();
    const images: AssetType[] = [];
    const videos: AssetType[] = [];

    for (const asset of assets) {
      if (asset.file === "image") images.push(asset);
      else if (asset.file === "video") videos.push(asset);
    }

    return { images, videos };
  }, [directories]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={css({ borderBottom: "1px solid", my: 4 })}>
          <h2 className={css({ fontSize: "xl", fontWeight: "medium" })}>
            Folders: {directories.length} / Assets:{" "}
            {assets.videos.length + assets.images.length} / Images:{" "}
            {assets.images.length} / Videos: {assets.videos.length}
          </h2>
        </div>
        <div
          className={css({
            display: "flex",
            flexWrap: "wrap",
            justifyItems: "center",
            justifyContent: "center",
            gap: 5,
          })}
        >
          {directories.map((subDirectory) => (
            <Folder
              key={subDirectory.hash}
              directory={subDirectory}
              isHomePage={true}
            />
          ))}
        </div>
        <Gallery title="Images" assets={assets.images} />
        <Gallery title="Videos" assets={assets.videos} />
      </div>
    </>
  );
};

export default Home;
